[tool.poetry]
name = "apolo11"
version = "0.1.0"
description = ""
authors = ["JORGE MOLINA Z <JGMOLZA@GMAIL.COM>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
